"""HITL approval file creation — Pending_Approval/ workflow."""
import uuid
from pathlib import Path
from datetime import datetime, timezone

ALLOWED_ACTION_TYPES = {"payment", "email_send", "file_delete", "other_sensitive"}


def create_approval_file(
    vault_path: Path,
    action_type: str,
    source_action_file: str,
    reason: str,
    details: dict,
) -> Path:
    """Create an approval request file in Pending_Approval/.

    Args:
        vault_path: Root of the Obsidian vault.
        action_type: One of ALLOWED_ACTION_TYPES.
        source_action_file: Relative path to the originating action file.
        reason: Human-readable reason for the approval request.
        details: Action-specific details dict (varies by action_type).

    Returns:
        Path to the created approval file in Pending_Approval/.

    Raises:
        ValueError: If action_type is not in ALLOWED_ACTION_TYPES.
    """
    if action_type not in ALLOWED_ACTION_TYPES:
        raise ValueError(
            f"Invalid action_type '{action_type}'. "
            f"Allowed: {sorted(ALLOWED_ACTION_TYPES)}"
        )

    vault_path = Path(vault_path)
    pending_dir = vault_path / "Pending_Approval"

    now = datetime.now(timezone.utc)
    timestamp = now.strftime("%Y%m%dT%H%M%SZ")
    filename = f"APPROVAL_{action_type}_{timestamp}.md"
    approval_path = pending_dir / filename

    entry_id = str(uuid.uuid4())
    iso_now = now.strftime("%Y-%m-%dT%H:%M:%SZ")

    details_yaml = "\n".join(f"  {k}: {v}" for k, v in details.items())
    details_md = "\n".join(f"- **{k}**: {v}" for k, v in details.items())

    content = f"""---
id: {entry_id}
type: approval_request
action_type: {action_type}
status: pending
source_action_file: {source_action_file}
reason: {reason}
created_at: {iso_now}
details:
{details_yaml if details_yaml else "  (none)"}
---

# Approval Required: {action_type.replace("_", " ").title()}

**Reason**: {reason}

## Action Details

{details_md if details_md else "_No additional details provided._"}

## Decision Instructions

To **APPROVE**: Move this file to `Approved/`
To **REJECT**: Move this file to `Rejected/`

> ⚠️ Do NOT edit this file. Only move it.
> Processing is paused until you make a decision.

---
*Created at {iso_now} by the AI Employee*
"""
    approval_path.write_text(content, encoding="utf-8")
    return approval_path
